language: java
jdk:
  - openjdk8
  - openjdk11
  - openjdk12
  - openjdk13
  #- openjdk-ea

#ignore default install step
install: true

cache:
  directories:
  - $HOME/.m2

script: ./mvnw clean verify
